#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Mar 08, 2019 07:36:47 AM EET  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set desc "-family {DejaVu Sans} -size 0"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 12"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 0"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 12"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 28 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font18
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 16 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font19
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m58" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1351x695+-10+14
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m58
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font {-family {DejaVu Sans} -size 12} \
        -foreground {#000000} -tearoff 0 
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font "TkDefaultFont"
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo59 \
        -width 1352 -height 693 -takefocus {} 
    vTcl:DefineAlias "$top.tNo59" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo59.t0 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo59.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo59 add $top.tNo59.t0 \
        -padding 0 -sticky nsew -state normal -text CameraUI -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo59.t0
    canvas $site_4_0.can60 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 431 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 1091 
    vTcl:DefineAlias "$site_4_0.can60" "StripCanvas1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Load Shelve} 
    vTcl:DefineAlias "$site_4_0.but61" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Save Shelve} 
    vTcl:DefineAlias "$site_4_0.but62" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_4_0.but63" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but64" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_4_0.but65" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_4_0.but66" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command LoadParticipantsCSV \
        -font TkDefaultFont -foreground {#000000} -highlightcolor black \
        -text {Load Participants} 
    vTcl:DefineAlias "$site_4_0.but67" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Load the participants csv}
    }
    button $site_4_0.but68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_4_0.but68" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command SaveResultsCSV -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {Save Results} 
    vTcl:DefineAlias "$site_4_0.but69" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but69 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save the results as CSV}
    }
    button $site_4_0.but70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but70" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but71" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but72" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but73 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but73" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but74" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command StripShowNormal -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {Normal Strip} 
    vTcl:DefineAlias "$site_4_0.but75" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but75 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Show the normal strip}
    }
    button $site_4_0.but76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command TimerStop -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {STOP TIMER} \
        -wraplength 70 
    vTcl:DefineAlias "$site_4_0.but76" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but76 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Stop the timer}
    }
    button $site_4_0.but79 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command TimerStart -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black \
        -text {START (TIMER) (CAPTURE)} -wraplength 70 
    vTcl:DefineAlias "$site_4_0.but79" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but79 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Start the Timer and camera capture}
    }
    scale $site_4_0.sca80 \
        -activebackground {#f9f9f9} -background {#d9d9d9} -bigincrement 0.0 \
        -font {-family {DejaVu Sans} -size 12} -foreground {#000000} \
        -from 0.0 -highlightcolor black -orient horizontal -resolution 1.0 \
        -sliderlength 50 -sliderrelief groove -tickinterval 1.0 -to 100.0 \
        -troughcolor {#d9d9d9} -variable StripScrollbarNumFrames -width 20 
    vTcl:DefineAlias "$site_4_0.sca80" "StripScrollScale1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.sca80 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Strip Scrollbar}
    }
    scale $site_4_0.sca84 \
        -activebackground {#f9f9f9} -background {#d9d9d9} -bigincrement 0.0 \
        -font {-family {DejaVu Sans} -size 12} -foreground {#000000} \
        -from 0.0 -highlightcolor black -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} \
        -variable CaptureSensitivityScale 
    vTcl:DefineAlias "$site_4_0.sca84" "CaptureSensScale1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.sca84 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Capture Sensitivity}
    }
    text $site_4_0.tex111 \
        -background white -font {-family {DejaVu Sans} -size 16} \
        -foreground black -height 36 -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 106 -wrap word 
    .top42.tNo59.t0.tex111 configure -font font19
    .top42.tNo59.t0.tex111 insert end text
    vTcl:DefineAlias "$site_4_0.tex111" "BibNumText2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.tex111 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Input Bib number of participant with corresponding line}
    }
    text $site_4_0.tex112 \
        -background white -font {-family {DejaVu Sans} -size 28 -weight bold} \
        -foreground black -height 36 -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 156 -wrap word 
    .top42.tNo59.t0.tex112 configure -font font18
    .top42.tNo59.t0.tex112 insert end text
    vTcl:DefineAlias "$site_4_0.tex112" "StripTimeText2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.tex112 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Time of the line on the strip}
    }
    text $site_4_0.tex113 \
        -background white -font {-family {DejaVu Sans} -size 28 -weight bold} \
        -foreground black -height 36 -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 156 -wrap word 
    .top42.tNo59.t0.tex113 configure -font font18
    .top42.tNo59.t0.tex113 insert end text
    vTcl:DefineAlias "$site_4_0.tex113" "TimerText2" vTcl:WidgetProc "Toplevel1" 1
    text $site_4_0.tex114 \
        -background white -font {-family {DejaVu Sans} -size 16} \
        -foreground black -height 36 -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 156 -wrap word 
    .top42.tNo59.t0.tex114 configure -font font19
    .top42.tNo59.t0.tex114 insert end text
    vTcl:DefineAlias "$site_4_0.tex114" "CurrentTimeText2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent115 \
        -background white -font {-family {DejaVu Sans Mono} -size 12} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent115" "SaveShelveEntry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent116 \
        -background white -font {-family {DejaVu Sans Mono} -size 12} \
        -foreground {#000000} -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent116" "LoadShelveEntry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab117 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Strip Time} 
    vTcl:DefineAlias "$site_4_0.lab117" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab118 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Current Time} 
    vTcl:DefineAlias "$site_4_0.lab118" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab119 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Timer 
    vTcl:DefineAlias "$site_4_0.lab119" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab120 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {BIB NUM} 
    vTcl:DefineAlias "$site_4_0.lab120" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but121 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command CapturePauseResume -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black \
        -text {PAUSE / RESUME (CAPTURE)} -wraplength 70 
    vTcl:DefineAlias "$site_4_0.but121" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but121 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Pause or resume camera capture}
    }
    button $site_4_0.but122 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command k5FramesGoForward -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {+5000 frames} 
    vTcl:DefineAlias "$site_4_0.but122" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but122 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go Forward 5000 frames}
    }
    button $site_4_0.but123 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command k5FramesGoBack -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {- 5000 frames} 
    vTcl:DefineAlias "$site_4_0.but123" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but123 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go Back 5000 frames}
    }
    scale $site_4_0.sca128 \
        -activebackground {#f9f9f9} -background {#d9d9d9} -bigincrement 0.0 \
        -font {-family {DejaVu Sans} -size 12} -foreground {#000000} \
        -from 0.0 -highlightcolor black -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$site_4_0.sca128" "Scale1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_4_0.tSe129
    vTcl:DefineAlias "$site_4_0.tSe129" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but139 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text <- -wraplength 70 
    vTcl:DefineAlias "$site_4_0.but139" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but140 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text -> -wraplength 70 
    vTcl:DefineAlias "$site_4_0.but140" "Button1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_4_0.tSe141 \
        -orient vertical 
    vTcl:DefineAlias "$site_4_0.tSe141" "TSeparator4" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_4_0.lab145 \
        -font TkDefaultFont -foreground black \
        -text {Results & YOLOv3 Objects} -background {#d9d9d9} -height 525 \
        -highlightcolor black -width 240 
    vTcl:DefineAlias "$site_4_0.lab145" "ResultsLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad146 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command FinishDirectionRtoL \
        -font TkDefaultFont -foreground {#000000} -highlightcolor black \
        -justify left -text {Right To Left} -variable FinishDirection 
    vTcl:DefineAlias "$site_4_0.rad146" "FinishDirectionRtoLRadiobutton2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.rad146 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set finishing direction right to left}
    }
    radiobutton $site_4_0.rad147 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command FinishDirectionLtoR \
        -font TkDefaultFont -foreground {#000000} -highlightcolor black \
        -justify left -text {Left To Right} -variable FinishDirection 
    vTcl:DefineAlias "$site_4_0.rad147" "FinishDirectionLtoRRadiobutton2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.rad147 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set finishing direction left to right}
    }
    button $site_4_0.but55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command StripDetectYoloV3 -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black \
        -text {Detect with YoloV3} 
    vTcl:DefineAlias "$site_4_0.but55" "YoloV3Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_0.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Detect Objects with Yolov3}
    }
    button $site_4_0.but56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but56" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.but57" "Button1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.can60 \
        -in $site_4_0 -x 0 -y 200 -width 1091 -relwidth 0 -height 431 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but61 \
        -in $site_4_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_4_0.but62 \
        -in $site_4_0 -x 10 -y 60 -width 99 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but63 \
        -in $site_4_0 -x 430 -y 10 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but64 \
        -in $site_4_0 -x 20 -y 100 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but65 \
        -in $site_4_0 -x 510 -y 10 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but66 \
        -in $site_4_0 -x 590 -y 10 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but67 \
        -in $site_4_0 -x 380 -y 50 -width 119 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but68 \
        -in $site_4_0 -x 510 -y 50 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but69 \
        -in $site_4_0 -x 590 -y 50 -width 99 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but70 \
        -in $site_4_0 -x 430 -y 90 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but71 \
        -in $site_4_0 -x 510 -y 90 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but72 \
        -in $site_4_0 -x 590 -y 90 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but73 \
        -in $site_4_0 -x 430 -y 142 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but74 \
        -in $site_4_0 -x 510 -y 142 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but75 \
        -in $site_4_0 -x 710 -y 170 -width 89 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but76 \
        -in $site_4_0 -x 1250 -y 10 -width 89 -relwidth 0 -height 98 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but79 \
        -in $site_4_0 -x 1050 -y 10 -width 89 -height 98 -anchor nw \
        -bordermode ignore 
    place $site_4_0.sca80 \
        -in $site_4_0 -x 10 -y 630 -width 1078 -height 64 -anchor nw \
        -bordermode ignore 
    place $site_4_0.sca84 \
        -in $site_4_0 -x 10 -y 150 -anchor nw -bordermode ignore 
    place $site_4_0.tex111 \
        -in $site_4_0 -x 990 -y 160 -width 106 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex112 \
        -in $site_4_0 -x 830 -y 160 -width 156 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex113 \
        -in $site_4_0 -x 883 -y 25 -width 156 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex114 \
        -in $site_4_0 -x 722 -y 25 -width 156 -height 36 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent115 \
        -in $site_4_0 -x 120 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.ent116 \
        -in $site_4_0 -x 120 -y 20 -width 166 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab117 \
        -in $site_4_0 -x 830 -y 140 -width 156 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab118 \
        -in $site_4_0 -x 720 -y 5 -width 156 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab119 \
        -in $site_4_0 -x 880 -y 6 -width 156 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab120 \
        -in $site_4_0 -x 990 -y 140 -width 96 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but121 \
        -in $site_4_0 -x 1150 -y 10 -width 89 -height 98 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but122 \
        -in $site_4_0 -x 885 -y 65 -width 149 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but123 \
        -in $site_4_0 -x 730 -y 65 -width 149 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.sca128 \
        -in $site_4_0 -x 720 -y 102 -width 318 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tSe129 \
        -in $site_4_0 -x 10 -y 140 -width 700 -anchor nw -bordermode inside 
    place $site_4_0.but139 \
        -in $site_4_0 -x 1110 -y 110 -width 89 -relwidth 0 -height 38 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but140 \
        -in $site_4_0 -x 1220 -y 110 -width 89 -height 38 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tSe141 \
        -in $site_4_0 -x 710 -y 0 -height 140 -anchor nw -bordermode inside 
    place $site_4_0.lab145 \
        -in $site_4_0 -x 1100 -y 147 -width 240 -relwidth 0 -height 525 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad146 \
        -in $site_4_0 -x 300 -y 110 -anchor nw -bordermode ignore 
    place $site_4_0.rad147 \
        -in $site_4_0 -x 200 -y 110 -width 101 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 590 -y 170 -width 119 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 430 -y 170 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but57 \
        -in $site_4_0 -x 510 -y 170 -width 69 -height 28 -anchor nw \
        -bordermode ignore 
    frame $top.tNo59.t2 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo59.t2" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo59 add $top.tNo59.t2 \
        -padding 0 -sticky nsew -state normal -text {Shelve Explorer} \
        -image {} -compound none -underline -1 
    set site_4_1  $top.tNo59.t2
    canvas $site_4_1.can103 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 351 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 1051 
    vTcl:DefineAlias "$site_4_1.can103" "ShelveExplorerCanvas3" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but104 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command StripGoLeft -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {Go Left} 
    vTcl:DefineAlias "$site_4_1.but104" "Button3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.but104 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go left on the strip (~1000 slices)}
    }
    button $site_4_1.but105 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command StripGoRight -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {Go Right} 
    vTcl:DefineAlias "$site_4_1.but105" "Button3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.but105 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Go right on the strip (~1000 slices)}
    }
    text $site_4_1.tex106 \
        -background white -font {-family {DejaVu Sans} -size 12} \
        -foreground black -height 46 -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 216 -wrap word 
    .top42.tNo59.t2.tex106 configure -font font21
    .top42.tNo59.t2.tex106 insert end text
    vTcl:DefineAlias "$site_4_1.tex106" "LineTimeText1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.tex106 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Time of the line on the strip}
    }
    text $site_4_1.tex107 \
        -background white -font {-family {DejaVu Sans} -size 16} \
        -foreground black -height 46 -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 126 -wrap word 
    .top42.tNo59.t2.tex107 configure -font font19
    .top42.tNo59.t2.tex107 insert end text
    vTcl:DefineAlias "$site_4_1.tex107" "BibNumText1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab108 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Time 
    vTcl:DefineAlias "$site_4_1.lab108" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_1.lab110 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {BIB NUM} 
    vTcl:DefineAlias "$site_4_1.lab110" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Delete Lines} 
    vTcl:DefineAlias "$site_4_1.but53" "Button3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_1.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Delete the lines from Canvas}
    }
    labelframe $site_4_1.lab59 \
        -font TkDefaultFont -foreground black \
        -text {Results & YOLOv3 Objects} -background {#d9d9d9} -height 525 \
        -highlightcolor black -width 270 
    vTcl:DefineAlias "$site_4_1.lab59" "ExplorerResultsLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.can103 \
        -in $site_4_1 -x 10 -y 190 -width 1051 -relwidth 0 -height 351 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but104 \
        -in $site_4_1 -x 440 -y 140 -width 119 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but105 \
        -in $site_4_1 -x 570 -y 140 -width 129 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tex106 \
        -in $site_4_1 -x 710 -y 140 -width 216 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.tex107 \
        -in $site_4_1 -x 930 -y 140 -width 126 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab108 \
        -in $site_4_1 -x 720 -y 110 -width 206 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab110 \
        -in $site_4_1 -x 930 -y 110 -width 126 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but53 \
        -in $site_4_1 -x 310 -y 140 -width 119 -height 48 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab59 \
        -in $site_4_1 -x 1070 -y 130 -width 270 -relwidth 0 -height 525 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo59.t1 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo59.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo59 add $top.tNo59.t1 \
        -padding 0 -sticky nsew -state normal -text {IDS Settings} -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo59.t1
    scale $site_4_2.sca85 \
        -activebackground {#f9f9f9} -background {#d9d9d9} -bigincrement 0.0 \
        -font {-family {DejaVu Sans} -size 12} -foreground {#000000} \
        -from 0.0 -highlightcolor black -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$site_4_2.sca85" "PixelClockScale1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.sca85 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set the Camera Pixel Clock}
    }
    scale $site_4_2.sca86 \
        -activebackground {#f9f9f9} -background {#d9d9d9} -bigincrement 0.0 \
        -font {-family {DejaVu Sans} -size 12} -foreground {#000000} \
        -from 0.0 -highlightcolor black -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$site_4_2.sca86" "IDSGainScale1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.sca86 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set the Camera Gain}
    }
    scale $site_4_2.sca87 \
        -activebackground {#f9f9f9} -background {#d9d9d9} -bigincrement 0.0 \
        -font {-family {DejaVu Sans} -size 12} -foreground {#000000} \
        -from 0.0 -highlightcolor black -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$site_4_2.sca87" "IDSExposureScale1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.sca87 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set the Camera Exposure time}
    }
    checkbutton $site_4_2.che88 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text {Auto exposure} \
        -variable che88 
    vTcl:DefineAlias "$site_4_2.che88" "IDSExposureCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.che88 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enable Auto Exposure on the Camera}
    }
    checkbutton $site_4_2.che89 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text Check -variable che88 
    vTcl:DefineAlias "$site_4_2.che89" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_2.che90 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text {Auto gain} -variable che88 
    vTcl:DefineAlias "$site_4_2.che90" "IDSGainCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.che90 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Enable Auto gain on the Camera}
    }
    button $site_4_2.but91 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Load Settings} 
    vTcl:DefineAlias "$site_4_2.but91" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.but91 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Load Camera settings}
    }
    button $site_4_2.but92 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Default settings} 
    vTcl:DefineAlias "$site_4_2.but92" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but93 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Save Settings} 
    vTcl:DefineAlias "$site_4_2.but93" "Button1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.but93 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save Camera Settings (opens filedialog)}
    }
    canvas $site_4_2.can94 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 561 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 491 
    vTcl:DefineAlias "$site_4_2.can94" "IDSPreviewCanvas2" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but95 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command IDSStopPreview -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {Stop Preview} 
    vTcl:DefineAlias "$site_4_2.but95" "IDSStopPreviewButton2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.but95 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Stop the Camera Preview}
    }
    button $site_4_2.but96 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command IDSStartPreview -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text {Start Preview} 
    vTcl:DefineAlias "$site_4_2.but96" "IDSStartButton2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.but96 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Start the Preview from the camera}
    }
    label $site_4_2.lab97 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Pixel Clock} 
    vTcl:DefineAlias "$site_4_2.lab97" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab98 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Gain + Gain boost} 
    vTcl:DefineAlias "$site_4_2.lab98" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab99 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Exposure time} 
    vTcl:DefineAlias "$site_4_2.lab99" "Label1" vTcl:WidgetProc "Toplevel1" 1
    scale $site_4_2.sca101 \
        -activebackground {#f9f9f9} -background {#d9d9d9} -bigincrement 0.0 \
        -font {-family {DejaVu Sans} -size 12} -foreground {#000000} \
        -from 0.0 -highlightcolor black -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor {#d9d9d9} \
        -variable IDSFramerateScale 
    vTcl:DefineAlias "$site_4_2.sca101" "IDSFramerateScale1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.sca101 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Set the Camera Framerate}
    }
    label $site_4_2.lab102 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Framerate 
    vTcl:DefineAlias "$site_4_2.lab102" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_2.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text FPS 
    vTcl:DefineAlias "$site_4_2.lab50" "Label4" vTcl:WidgetProc "Toplevel1" 1
    bind $site_4_2.lab50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Framerate reported by the camera}
    }
    label $site_4_2.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text FPS 
    vTcl:DefineAlias "$site_4_2.lab51" "Label5" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.sca85 \
        -in $site_4_2 -x 40 -y 110 -width 308 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_2.sca86 \
        -in $site_4_2 -x 40 -y 180 -width 308 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_2.sca87 \
        -in $site_4_2 -x 40 -y 250 -width 308 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_2.che88 \
        -in $site_4_2 -x 380 -y 250 -width 112 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.che89 \
        -in $site_4_2 -x 390 -y 350 -width 72 -height 50 -anchor nw \
        -bordermode ignore 
    place $site_4_2.che90 \
        -in $site_4_2 -x 370 -y 180 -width 102 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but91 \
        -in $site_4_2 -x 150 -y 30 -anchor nw -bordermode ignore 
    place $site_4_2.but92 \
        -in $site_4_2 -x 290 -y 30 -width 119 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but93 \
        -in $site_4_2 -x 20 -y 30 -width 109 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.can94 \
        -in $site_4_2 -x 820 -y 90 -width 491 -relwidth 0 -height 561 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but95 \
        -in $site_4_2 -x 950 -y 20 -width 106 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but96 \
        -in $site_4_2 -x 830 -y 20 -width 106 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab97 \
        -in $site_4_2 -x 40 -y 90 -width 77 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab98 \
        -in $site_4_2 -x 30 -y 160 -width 137 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab99 \
        -in $site_4_2 -x 10 -y 230 -width 127 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_4_2.sca101 \
        -in $site_4_2 -x 390 -y 110 -width 308 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab102 \
        -in $site_4_2 -x 390 -y 90 -width 77 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab50 \
        -in $site_4_2 -x 1070 -y 60 -anchor nw -bordermode ignore 
    place $site_4_2.lab51 \
        -in $site_4_2 -x 1110 -y 60 -anchor nw -bordermode ignore 
    ttk::style configure TSizegrip -background #d9d9d9
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi126 \
        -cursor bottom_right_corner 
    vTcl:DefineAlias "$top.tSi126" "TSizegrip1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo59 \
        -in $top -x 0 -y 0 -width 1352 -relwidth 0 -height 693 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSi126 \
        -in $top -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}
#############################################################################
## Binding tag:  _vTclBalloon


if {![info exists vTcl(sourcing)]} {
bind "_vTclBalloon" <<KillBalloon>> {
    namespace eval ::vTcl::balloon {
        after cancel $id
        if {[winfo exists .vTcl.balloon]} {
            destroy .vTcl.balloon
        }
        set set 0
    }
}
bind "_vTclBalloon" <<vTclBalloon>> {
    if {$::vTcl::balloon::first != 1} {break}
    namespace eval ::vTcl::balloon {
        set first 2
        if {![winfo exists .vTcl]} {
            toplevel .vTcl; wm withdraw .vTcl
        }
        if {![winfo exists .vTcl.balloon]} {
            toplevel .vTcl.balloon -bg black
        }
        wm overrideredirect .vTcl.balloon 1
        label .vTcl.balloon.l  -text ${%W} -relief flat  -bg #ffffaa -fg black -padx 2 -pady 0 -anchor w
        pack .vTcl.balloon.l -side left -padx 1 -pady 1
        wm geometry  .vTcl.balloon  +[expr {[winfo rootx %W]+[winfo width %W]/2}]+[expr {[winfo rooty %W]+[winfo height %W]+4}]
        set set 1
    }
}
bind "_vTclBalloon" <Button> {
    namespace eval ::vTcl::balloon {
        set first 0
    }
    vTcl:FireEvent %W <<KillBalloon>>
}
bind "_vTclBalloon" <Enter> {
    namespace eval ::vTcl::balloon {
        ## self defining balloon?
        if {![info exists %W]} {
            vTcl:FireEvent %W <<SetBalloon>>
        }
        set set 0
        set first 1
        set id [after 500 {vTcl:FireEvent %W <<vTclBalloon>>}]
    }
}
bind "_vTclBalloon" <Leave> {
    namespace eval ::vTcl::balloon {
        set first 0
    }
    vTcl:FireEvent %W <<KillBalloon>>
}
bind "_vTclBalloon" <Motion> {
    namespace eval ::vTcl::balloon {
        if {!$set} {
            after cancel $id
            set id [after 500 {vTcl:FireEvent %W <<vTclBalloon>>}]
        }
    }
}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

